import type { FreeBot } from './types';
import { localize } from '@deriv-com/translations';

/**
 * Free Bots catalog.
 *
 * The Free Bots tab remains available. Add a new bot by appending an entry below.
 * Users can Run it immediately or Load it into Bot Builder.
 */
export const FREE_BOTS: FreeBot[] = [
    {
        id: 'consecutive-digits-over',
        title: localize('Digit Successor Differs'),
        description: localize(
            'Within your tick window, maps what followed each digit 0–9. When the current digit is X and X→Y was seen, places Digit Differs on Y. Uses payout-based recovery (default 9.6%).'
        ),
        tags: [localize('Differs'), localize('Successor'), localize('Recovery')],
        strategy: 'CONSECUTIVE_DIGITS_OVER',
        form: {
            symbol: '1HZ75V',
            tradetype: 'matchesdiffers',
            type: 'DIGITDIFF',
            stake: '1',
            duration: '1',
            durationtype: 't',
            tick_window: '5',
            pattern_threshold: '1',
            payout_percent: '9.6',
            recovery_splits: '1',
            boolean_strategy: true,
            boolean_journal: true,
            profit: '5',
            loss: '2',
        },
    },
    {
        id: 'window-index-differs',
        title: localize('Same-Digit Wait Differs'),
        description: localize(
            'When previous last digit equals current last digit, waits N ticks (default 2), then Differs that repeated digit. Same payout recovery as bot #1 (default 9.6%).'
        ),
        tags: [localize('Differs'), localize('Repeat'), localize('Recovery')],
        strategy: 'WINDOW_INDEX_DIFFERS',
        form: {
            symbol: '1HZ75V',
            tradetype: 'matchesdiffers',
            type: 'DIGITDIFF',
            stake: '1',
            duration: '1',
            durationtype: 't',
            trade_wait: '2',
            payout_percent: '9.6',
            recovery_splits: '1',
            boolean_strategy: true,
            boolean_journal: true,
            profit: '5',
            loss: '2',
        },
    },
    {
        id: 'strategy-voting',
        title: localize('Strategy Voting Differs'),
        description: localize(
            'Runs 18 Digit Differs strategies each tick, weights their votes, and Differs the highest-confidence digit when confidence ≥ 70% with no ties. Same payout recovery as bot #1 (default 9.6%).'
        ),
        tags: [localize('Differs'), localize('Voting'), localize('Recovery')],
        strategy: 'STRATEGY_VOTING',
        form: {
            symbol: '1HZ75V',
            tradetype: 'matchesdiffers',
            type: 'DIGITDIFF',
            stake: '1',
            duration: '1',
            durationtype: 't',
            tick_window: '50',
            confidence_threshold: '70',
            min_voting_strategies: '3',
            max_abstaining_strategies: '15',
            payout_percent: '9.6',
            recovery_splits: '1',
            boolean_strategy: true,
            boolean_journal: true,
            boolean_vote_summary: true,
            boolean_tie_rejection: true,
            boolean_debug: false,
            boolean_sv_digit_successor: true,
            weight_sv_digit_successor: '1.5',
            boolean_sv_complement_digit: true,
            weight_sv_complement_digit: '1.2',
            boolean_sv_digit_transition: true,
            weight_sv_digit_transition: '1.0',
            boolean_sv_cold_digit: true,
            weight_sv_cold_digit: '2.0',
            boolean_sv_least_frequent: true,
            weight_sv_least_frequent: '1.4',
            boolean_sv_most_frequent: true,
            weight_sv_most_frequent: '1.0',
            boolean_sv_streak_breaker: true,
            weight_sv_streak_breaker: '1.8',
            boolean_sv_last_repeat: true,
            weight_sv_last_repeat: '1.3',
            boolean_sv_absent_digit: true,
            weight_sv_absent_digit: '1.6',
            boolean_sv_second_last: true,
            weight_sv_second_last: '0.9',
            boolean_sv_parity_fade: true,
            weight_sv_parity_fade: '1.1',
            boolean_sv_edge_fade: true,
            weight_sv_edge_fade: '1.0',
            boolean_sv_oscillation: true,
            weight_sv_oscillation: '1.3',
            boolean_sv_mid_range: true,
            weight_sv_mid_range: '1.0',
            boolean_sv_rising_run: true,
            weight_sv_rising_run: '1.2',
            boolean_sv_falling_run: true,
            weight_sv_falling_run: '1.2',
            boolean_sv_unique_tail: true,
            weight_sv_unique_tail: '1.1',
            boolean_sv_modal_neighbor: true,
            weight_sv_modal_neighbor: '1.0',
            profit: '5',
            loss: '2',
        },
    },
];
