import { localize } from '@deriv-com/translations';
import type { FreeBot } from './types';

/**
 * Free Bots catalog.
 *
 * Add a new bot by appending an entry below, then push.
 * Users can Run it immediately or Load it into Bot Builder.
 *
 * Tip: keep stakes/demo-friendly defaults. Custom Blockly XML bots can be
 * added later as a separate kind once you share the ideas.
 */
export const FREE_BOTS: FreeBot[] = [
    {
        id: 'range-momentum-over-one',
        title: localize('Range Momentum Over 1'),
        description: localize(
            'Places Over 1 when digits move Lower(2–5)→Higher(6–9) with no Losing(0–1) digits in the lookback window. Optional cooldown, Martingale, and consecutive-loss stop. Run once calls Range Momentum Numbers then Range Momentum Booleans.'
        ),
        tags: [localize('Over 1'), localize('Momentum'), localize('Range')],
        strategy: 'RANGE_MOMENTUM_OVER_ONE',
        form: {
            symbol: '1HZ75V',
            tradetype: 'overunder',
            type: 'DIGITOVER',
            stake: '1',
            duration: '1',
            durationtype: 't',
            cooldown_after_trade: '0',
            losing_lookback: '2',
            boolean_strategy: true,
            boolean_journal: true,
            boolean_notify: true,
            boolean_martingale: true,
            profit: '5',
            loss: '5',
            size: '2',
        },
    },
    {
        id: 'increasing-gap-differs',
        title: localize('Increasing Gap Differs'),
        description: localize(
            'Tracks each digit 0–9 for arithmetic gap progressions (e.g. 2→3→4 predicts gap 5). Waits the predicted gap, then Differs that digit. Optional early cancellation, cooldown, and Martingale.'
        ),
        tags: [localize('Differs'), localize('Gap'), localize('Progression')],
        strategy: 'INCREASING_GAP_DIFFERS',
        form: {
            symbol: '1HZ75V',
            tradetype: 'matchesdiffers',
            type: 'DIGITDIFF',
            stake: '1',
            duration: '1',
            durationtype: 't',
            min_gap: '1',
            max_gap: '20',
            min_common_diff: '1',
            max_common_diff: '5',
            gaps_required: '3',
            cooldown_after_trade: '0',
            max_trades_per_session: '0',
            boolean_strategy: true,
            boolean_journal: true,
            boolean_cancel_early: true,
            boolean_one_trade_per_cycle: true,
            boolean_one_active_trade: true,
            boolean_martingale: true,
            profit: '5',
            loss: '5',
            size: '2',
        },
    },
    {
        id: 'signal-score-differs',
        title: localize('Signal Score Differs'),
        description: localize(
            'Scores each digit from modular conditions and Differs the highest scorer when total score meets your minimum. Includes live score dashboard and detailed journal breakdown.'
        ),
        tags: [localize('Differs'), localize('Score'), localize('Modular')],
        strategy: 'SIGNAL_SCORE_DIFFERS',
        form: {
            symbol: '1HZ75V',
            tradetype: 'matchesdiffers',
            type: 'DIGITDIFF',
            stake: '1',
            duration: '1',
            durationtype: 't',
            min_signal_score: '6',
            frequency_window: '30',
            recent_appearance_window: '5',
            long_absence_threshold: '30',
            spike_recent_window: '10',
            spike_historical_window: '50',
            min_gap: '1',
            max_gap: '20',
            most_frequent_score: '2',
            repeated_gap_score: '3',
            recent_double_score: '2',
            frequency_spike_score: '2',
            long_absence_score: '-1',
            most_frequent_enabled: true,
            repeated_gap_enabled: true,
            recent_double_enabled: true,
            frequency_spike_enabled: true,
            long_absence_enabled: true,
            boolean_most_frequent: true,
            boolean_repeated_gap: true,
            boolean_recent_double: true,
            boolean_frequency_spike: true,
            boolean_long_absence: true,
            cooldown_after_trade: '0',
            max_trades_per_session: '0',
            boolean_strategy: true,
            boolean_journal: true,
            boolean_dashboard: true,
            boolean_one_active_trade: true,
            boolean_martingale: true,
            profit: '5',
            loss: '5',
            size: '2',
        },
    },
    {
        id: 'long-absence-return-differs',
        title: localize('Long-Absence Return Differs'),
        description: localize(
            'Tracks absence per digit. When a digit returns after a long absence, waits a configurable delay, then Differs that digit. Optional confirmation mode, early cancellation, and Martingale.'
        ),
        tags: [localize('Differs'), localize('Absence'), localize('Return')],
        strategy: 'LONG_ABSENCE_RETURN_DIFFERS',
        form: {
            symbol: '1HZ75V',
            tradetype: 'matchesdiffers',
            type: 'DIGITDIFF',
            stake: '1',
            duration: '1',
            durationtype: 't',
            min_absence_threshold: '20',
            max_absence_threshold: '0',
            return_delay: '2',
            required_return_confirmations: '1',
            confirmation_window: '5',
            max_signal_age: '0',
            cooldown_after_trade: '0',
            max_trades_per_session: '0',
            boolean_strategy: true,
            boolean_journal: true,
            boolean_cancel_early: true,
            boolean_dashboard: true,
            boolean_one_active_trade: true,
            boolean_martingale: true,
            profit: '5',
            loss: '5',
            size: '2',
        },
    },
    {
        id: 'conditional-even-odd-differs',
        title: localize('Conditional Differs With Even/Odd Filter'),
        description: localize(
            'Requires a primary Digit Differs signal plus even/odd parity confirmation before trading. Default uses Signal Score with matching-parity dominance.'
        ),
        tags: [localize('Differs'), localize('Even/Odd'), localize('Filter')],
        strategy: 'CONDITIONAL_EVEN_ODD_DIFFERS',
        form: {
            symbol: '1HZ75V',
            tradetype: 'matchesdiffers',
            type: 'DIGITDIFF',
            stake: '1',
            duration: '1',
            durationtype: 't',
            boolean_even_odd_filter: true,
            parity_window: '10',
            filter_mode: '0',
            threshold_type: '0',
            matching_parity_count: '7',
            matching_parity_percent: '70',
            required_confirmations: '1',
            max_signal_age: '2',
            primary_signal_source: 'signal_score',
            cooldown_after_trade: '0',
            max_trades_per_session: '0',
            boolean_strategy: true,
            boolean_journal: true,
            boolean_dashboard: true,
            boolean_one_active_trade: true,
            boolean_martingale: true,
            profit: '5',
            loss: '5',
            size: '2',
        },
    },
    {
        id: 'conditional-high-low-differs',
        title: localize('Conditional Differs With High/Low Filter'),
        description: localize(
            'Requires a primary Digit Differs signal plus High/Low group confirmation. Default uses Primary + Group Leader mode with most-frequent confirmation.'
        ),
        tags: [localize('Differs'), localize('High/Low'), localize('Filter')],
        strategy: 'CONDITIONAL_HIGH_LOW_DIFFERS',
        form: {
            symbol: '1HZ75V',
            tradetype: 'matchesdiffers',
            type: 'DIGITDIFF',
            stake: '1',
            duration: '1',
            durationtype: 't',
            boolean_high_low_filter: true,
            analysis_window: '10',
            filter_mode: '3',
            threshold_type: '0',
            dominant_group_count: '7',
            dominance_percent: '70',
            boolean_require_most_frequent: true,
            min_target_appearances: '2',
            min_target_group_share: '25',
            tie_action: '0',
            required_confirmations: '1',
            max_signal_age: '2',
            primary_signal_source: 'most_frequent',
            cooldown_after_trade: '0',
            max_trades_per_session: '0',
            boolean_strategy: true,
            boolean_journal: true,
            boolean_dashboard: true,
            boolean_one_active_trade: true,
            boolean_martingale: true,
            profit: '5',
            loss: '5',
            size: '2',
        },
    },
];
